<script setup lang="ts">
import { onUnmounted, ref, watch } from 'vue'
const props=defineProps<{invoke:<T>(action:string,payload?:Record<string,unknown>)=>Promise<T>;roles:{key:string;label:string;role:{ref:string};account:{ref:string}}[]}>()
interface Row {id:string;time:string;action:string;change:string;deduct?:string;item?:string}
interface Archive {rows:Row[];total:number;next_offset:number|null;totals:Record<string,string>;coverage:Record<string,number>;unknown_amounts:number;revision:number;saved_ms:number;note:string}
interface Job {ref:string;state:string;sequence:number;pages:number;count:number}
const categories=ref<{id:string;label:string}[]>([]),selection=ref(''),category=ref(''),direction=ref('all'),month=ref(''),query=ref(''),archive=ref<Archive|null>(null),job=ref<Job|null>(null),busy=ref(false),error=ref(''),notice=ref(''),confirmRemove=ref(false)
let disposed=false
const stopping=ref(false)
function choice(){const r=props.roles.find(r=>r.key===selection.value);if(!r)throw new Error('请选择已授权角色。');return {account_ref:r.account.ref,role_ref:r.role.ref,category:category.value,direction:direction.value}}
async function run(work:()=>Promise<void>){if(busy.value)return;busy.value=true;error.value='';notice.value='';try{await work()}catch(e){error.value=e instanceof Error?e.message:'资产记录操作未完成。'}finally{busy.value=false}}
async function load(offset=0){const result=await props.invoke<Archive>('billing.archive.get',{...choice(),offset,month:month.value,query:query.value.trim()});archive.value=offset&&archive.value?{...result,rows:[...archive.value.rows,...result.rows]}:result;confirmRemove.value=false}
async function collect(){await run(async()=>{stopping.value=false;job.value=(await props.invoke<{job:Job}>('billing.sync.start',choice())).job;try{while(!disposed&&!stopping.value&&job.value.state==='running'){job.value=(await props.invoke<{job:Job}>('billing.sync.step',{ref:job.value.ref,sequence:job.value.sequence})).job}if(job.value.state==='completed'){notice.value=`已收集 ${job.value.pages} 页，档案共 ${job.value.count} 条记录。`;if(!disposed)await load()}else notice.value='已停止收集，原档案保持不变。'}finally{await props.invoke('billing.sync.cancel',{ref:job.value.ref}).catch(()=>{});job.value=null}})}
watch([selection,category,direction],()=>{archive.value=null;confirmRemove.value=false;error.value='';notice.value=''})
void run(async()=>{categories.value=(await props.invoke<{categories:{id:string;label:string}[]}>('billing.schema')).categories;category.value=categories.value[0]?.id??''})
onUnmounted(()=>{disposed=true;stopping.value=true})
</script>
<template><section><h2>官方资产变动记录</h2><p>读取官方当前可提供的记录，成功读完才合并保存。这里的数值是游戏资产变化，不是实际支付金额。</p><form class="query-form" @submit.prevent="run(()=>load())"><label class="wide">游戏角色<select v-model="selection" :disabled="busy"><option value="">选择角色</option><option v-for="r in roles" :key="r.key" :value="r.key">{{r.label}}</option></select></label><label>资产类别<select v-model="category" :disabled="busy"><option v-for="c in categories" :key="c.id" :value="c.id">{{c.label}}</option></select></label><label>方向<select v-model="direction" :disabled="busy"><option value="all">全部变动</option><option value="produce">获得</option><option value="consume">消耗</option></select></label><div class="actions wide"><button :disabled="busy||!selection">查看已保存记录</button><button type="button" :disabled="busy||!selection" @click="collect">收集官方记录</button><button v-if="job" type="button" :disabled="stopping" @click="stopping=true">停止收集</button></div></form><p v-if="job" role="status">已读取 {{job.pages}} 页、{{job.count}} 条；停止后保留原档案。</p><p v-if="error" class="feedback danger" role="alert">{{error}}</p><p v-if="notice" class="feedback" role="status">{{notice}}</p></section>
<section v-if="archive"><h2>已保存档案</h2><form class="query-form" @submit.prevent="run(()=>load())"><label>月份<input v-model="month" type="month" :disabled="busy"></label><label>来源或物品<input v-model="query" maxlength="128" :disabled="busy"></label><button :disabled="busy">筛选档案</button></form><p>符合条件 {{archive.total}} 条；保存时间：{{archive.saved_ms?new Date(archive.saved_ms).toLocaleString():'尚未保存'}}。{{archive.note}}</p><ul><li v-for="(total,action) in archive.totals" :key="action">{{action||'未注明来源'}}：{{total}}（{{archive.coverage[action]}} 条有数值记录）</li></ul><p v-if="archive.unknown_amounts">另有 {{archive.unknown_amounts}} 条未提供可统计数值，未计入合计。</p><div class="table-scroll"><table><thead><tr><th>时间</th><th>来源 / 物品</th><th>变动</th><th>扣除</th><th>官方编号</th></tr></thead><tbody><tr v-for="(r,i) in archive.rows" :key="r.id||i"><td>{{r.time||'未提供'}}</td><td>{{r.action}} {{r.item}}</td><td>{{r.change||'未提供'}}</td><td>{{r.deduct||'—'}}</td><td>{{r.id||'无编号（本轮快照）'}}</td></tr></tbody></table></div><button v-if="archive.next_offset!==null" :disabled="busy" @click="run(()=>load(archive!.next_offset!))">更多记录</button><div class="actions"><label class="check"><input v-model="confirmRemove" type="checkbox" :disabled="busy">清空所选类别与方向的本地档案</label><button :disabled="busy||!confirmRemove" @click="run(async()=>{await invoke('billing.archive.remove',{...choice(),revision:archive!.revision,confirm:true});await load()})">确认清空</button></div></section></template>
