<script setup lang="ts">
import{ref,watch}from'vue'
import BusinessView,{type View}from'./BusinessView.vue'
const props=defineProps<{invoke:<T>(action:string,payload?:Record<string,unknown>)=>Promise<T>;roles:{key:string;label:string;role:{ref:string};account:{ref:string}}[]}>()
const selection=ref(''),code=ref(''),items=ref<{id:string;name:string;num:number;needed:number}[]>([]),view=ref<View|null>(null),busy=ref(false),error=ref('')
watch([selection,code],()=>{items.value=[];view.value=null})
async function run(compute=false){if(busy.value)return;busy.value=true;error.value='';view.value=null;try{const r=props.roles.find(r=>r.key===selection.value);if(!r)throw Error('请选择已授权的原神角色。');const result=await props.invoke<{items:{id:string;name:string;num:number}[];view:View}>(compute?'blueprint.compute':'blueprint.read',{account_ref:r.account.ref,role_ref:r.role.ref,...(compute?{list:items.value.filter(v=>v.needed>0).map(v=>({id:Number(v.id),cnt:v.needed}))}:{share_code:code.value.trim()})});view.value=result.view;if(!compute)items.value=result.items.map(v=>({...v,needed:Number(v.num)}))}catch(e){error.value=e instanceof Error?e.message:'摹本查询未完成。'}finally{busy.value=false}}
</script>
<template><section><h2>尘歌壶摹本计算</h2><form class="query-form" @submit.prevent="run()"><label class="wide">原神角色<select v-model="selection" :disabled="busy"><option value="">选择已授权角色</option><option v-for="r in roles" :key="r.key" :value="r.key">{{r.label}}</option></select></label><label>分享码<input v-model="code" inputmode="numeric" pattern="[0-9]{10,15}" required :disabled="busy"></label><button :disabled="busy||!selection">读取摹本摆设</button></form><p v-if="error" role="alert" class="feedback danger">{{error}}</p><form v-if="items.length" @submit.prevent="run(true)"><p>可按已持有的摆设减少需要制作的数量；不会读取库存或消耗材料。</p><div class="furniture"><label v-for="v in items" :key="v.id">{{v.name}} · 摹本需要 {{v.num}}<input v-model.number="v.needed" type="number" min="0" max="9999" step="1" :disabled="busy" required></label></div><button :disabled="busy||!items.some(v=>v.needed>0)">计算所选摆设材料</button></form><BusinessView v-if="view" :value="view"/></section></template>
<style scoped>.furniture{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:12px;margin-block:16px}label{display:grid;gap:8px;min-width:0}input,select{min-width:0}</style>
