<script setup lang="ts">
import { computed, onUnmounted, ref, watch } from 'vue'
import type { BuildConditions } from './build'
interface Field { key:string;label:string;unit:string;max:number }
interface Preset {ref:string;revision:number;name:string;character_id:string;conditions:BuildConditions}
const props=defineProps<{game:string;characterId:string;modelValue:BuildConditions|null;disabled:boolean;invoke:<T>(action:string,payload?:Record<string,unknown>)=>Promise<T>}>()
const emit=defineEmits<{ 'update:modelValue':[value:BuildConditions|null] }>()
const fields=ref<Field[]>([]),presets=ref<Preset[]>([]),preset=ref(''),name=ref(''),query=ref(''),source=ref(-1),field=ref('atkPct'),amount=ref(0),error=ref(''),busy=ref(false),notice=ref(''),confirm=ref<HTMLDialogElement|null>(null)
let disposed=false
const available=computed(()=>presets.value.filter(p=>p.character_id===props.characterId))
const selected=computed(()=>presets.value.find(p=>p.ref===preset.value))
const rows=computed(()=>props.modelValue?[{name:'自身额外增益',bonuses:props.modelValue.bonuses,index:-1},...props.modelValue.team.map((t,index)=>({...t,index}))]:[])
function update(fn:(c:BuildConditions)=>void){const c=JSON.parse(JSON.stringify(props.modelValue??{disable_character:false,disable_weapon:false,disable_equipment:false,bonuses:{},team:[]})) as BuildConditions;fn(c);emit('update:modelValue',c);notice.value=''}
function enabled(event:Event){if((event.target as HTMLInputElement).checked)update(()=>{});else emit('update:modelValue',null)}
async function load(){try{const [schema,list]=await Promise.all([props.invoke<{fields:Field[]}>('build.conditions'),props.invoke<{items:Preset[]}>('build.presets.list')]);if(!disposed){fields.value=schema.fields;presets.value=list.items}}catch(e){if(!disposed)error.value=e instanceof Error?e.message:'方案资料读取失败。'}}
void load();onUnmounted(()=>{disposed=true})
watch(()=>props.characterId,()=>{preset.value='';name.value='';source.value=-1;error.value='';emit('update:modelValue',null)})
function loadPreset(){if(!selected.value)return;name.value=selected.value.name;emit('update:modelValue',JSON.parse(JSON.stringify(selected.value.conditions)));source.value=-1;notice.value='方案已载入，请重新计算。'}
async function addTeammate(){if(busy.value||!props.modelValue)return;busy.value=true;error.value='';try{const result=await props.invoke<{entries:{id:string;name:string}[]}>('catalog.search',{kind:'character',query:query.value.trim()});const exact=result.entries.filter(e=>e.name===query.value.trim()||e.id===query.value.trim());const found=exact.length===1?exact[0]:result.entries.length===1?result.entries[0]:undefined;if(!found||found.id===props.characterId||props.modelValue.team.some(t=>t.character_id===found.id))throw Error('请填写唯一匹配且不重复的队友名称或 ID。');if(!disposed){update(c=>c.team.push({character_id:found.id,name:found.name,bonuses:{}}));query.value=''}}catch(e){if(!disposed)error.value=e instanceof Error?e.message:'队友查询失败。'}finally{busy.value=false}}
function addBonus(){const schema=fields.value.find(f=>f.key===field.value);if(!schema||!Number.isFinite(amount.value)||amount.value<0||amount.value>schema.max){error.value='请在所列范围内填写增益。';return}update(c=>{const target=source.value<0?c.bonuses:c.team[source.value]?.bonuses;if(target)target[field.value]=Number(amount.value)});error.value=''}
async function save(asNew:boolean){if(!props.modelValue||busy.value)return;busy.value=true;error.value='';try{const existing=asNew?undefined:selected.value;const result=await props.invoke<{items:Preset[];preset:Preset}>('build.presets.save',{name:name.value,character_id:props.characterId,conditions:props.modelValue,...(existing?{ref:existing.ref,revision:existing.revision}:{})});if(!disposed){presets.value=result.items;preset.value=result.preset.ref;notice.value='方案已保存。'}}catch(e){if(!disposed)error.value=e instanceof Error?e.message:'方案保存失败。'}finally{busy.value=false}}
async function remove(){const p=selected.value;if(!p)return;busy.value=true;error.value='';try{const result=await props.invoke<{items:Preset[]}>('build.presets.remove',{ref:p.ref,revision:p.revision});if(!disposed){presets.value=result.items;preset.value='';notice.value='方案已删除。';confirm.value?.close()}}catch(e){error.value=e instanceof Error?e.message:'方案删除失败。'}finally{busy.value=false}}
</script>
<template>
 <section class="build-conditions">
  <label class="check"><input type="checkbox" :checked="modelValue!==null" :disabled="disabled||busy" @change="enabled">建立自定义队伍与条件候选</label>
  <div class="plan-picker"><label>本角色已保存方案<select v-model="preset" :disabled="disabled||busy"><option value="">选择方案</option><option v-for="p in available" :key="p.ref" :value="p.ref">{{p.name}}</option></select></label><button type="button" :disabled="!selected||disabled||busy" @click="loadPreset">载入方案</button></div>
  <fieldset v-if="modelValue" :disabled="disabled||busy"><legend class="sr-only">自定义候选条件</legend>
   <p class="hint">基准保留原参考情境。候选应用下列数值；队友只标记增益来源，请按实际技能与装备填写，未填写的增益不会自动补满。静态面板和装备主副属性保留。</p>
   <div class="condition-flags"><label class="check"><input type="checkbox" :checked="modelValue.disable_character" @change="update(c=>c.disable_character=($event.target as HTMLInputElement).checked)">关闭角色局内参考增益</label><label class="check"><input type="checkbox" :checked="modelValue.disable_weapon" @change="update(c=>c.disable_weapon=($event.target as HTMLInputElement).checked)">关闭武器局内参考增益</label><label class="check"><input type="checkbox" :checked="modelValue.disable_equipment" @change="update(c=>c.disable_equipment=($event.target as HTMLInputElement).checked)">关闭套装局内参考增益</label></div>
   <label>候选敌人抗性（%，留空沿用参考）<input type="number" min="-100" max="100" step="any" :value="modelValue.enemy_resistance??''" @input="update(c=>{const v=($event.target as HTMLInputElement).value;if(v==='')delete c.enemy_resistance;else c.enemy_resistance=Number(v)})"></label>
   <div class="plan-picker"><label>添加模拟队友<input v-model="query" placeholder="角色名称或 ID"></label><button type="button" :disabled="!query.trim()||modelValue.team.length>=(game==='zzz'?2:3)" @click="addTeammate">添加队友</button></div>
   <ul class="team-members"><li v-for="(t,index) in modelValue.team" :key="t.character_id">{{t.name}}<button type="button" :aria-label="`移除队友${t.name}`" @click="update(c=>c.team.splice(index,1));source=-1">移除</button></li></ul>
   <div class="bonus-entry"><label>增益来源<select v-model.number="source"><option :value="-1">自身额外增益</option><option v-for="(t,index) in modelValue.team" :key="t.character_id" :value="index">{{t.name}}</option></select></label><label>增益类型<select v-model="field"><option v-for="f in fields" :key="f.key" :value="f.key">{{f.label}}（{{f.unit}}）</option></select></label><label>增益数值<input v-model.number="amount" type="number" min="0" :max="fields.find(f=>f.key===field)?.max" step="any"></label><button type="button" @click="addBonus">应用此增益</button></div>
   <div v-for="row in rows.filter(r=>Object.keys(r.bonuses).length)" :key="row.index" class="condition-values"><h4>{{row.name}}</h4><ul><li v-for="(value,key) in row.bonuses" :key="key"><span>{{fields.find(f=>f.key===key)?.label}}：{{value}}{{fields.find(f=>f.key===key)?.unit}}</span><button type="button" :aria-label="`移除${row.name}的${fields.find(f=>f.key===key)?.label}`" @click="update(c=>{const b=row.index<0?c.bonuses:c.team[row.index]!.bonuses;delete b[key]})">移除</button></li></ul></div>
   <label>方案名称<input v-model="name" maxlength="40" placeholder="例如：日常队伍"></label><div class="actions"><button type="button" :disabled="!name.trim()" @click="save(true)">保存为新方案</button><button type="button" :disabled="!selected||!name.trim()" @click="save(false)">更新所选方案</button><button type="button" :disabled="!selected" @click="confirm?.showModal()">删除所选方案</button></div>
  </fieldset>
  <p v-if="error" role="alert" class="danger-text">{{error}}</p><p v-if="notice" role="status" class="hint">{{notice}}</p>
  <dialog ref="confirm"><h3>删除方案 {{selected?.name}}</h3><p>只删除本地模拟方案，不修改游戏角色或账号。</p><div class="actions"><button type="button" autofocus :disabled="busy" @click="confirm?.close()">取消</button><button type="button" :disabled="busy" @click="remove">确认删除方案</button></div></dialog>
 </section>
</template>
<style scoped>
.build-conditions{display:grid;gap:16px;margin:20px 0;padding:20px 0;border-block:1px solid var(--raylea-color-border)}.build-conditions fieldset{display:grid;gap:16px;border:0;padding:0;min-width:0}.build-conditions label:not(.check){display:grid;gap:8px;min-width:0}.plan-picker{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:12px;align-items:end}.condition-flags{display:grid;gap:12px}.team-members,.condition-values ul{list-style:none;padding:0;margin:0}.team-members li,.condition-values li{display:flex;justify-content:space-between;gap:16px;align-items:center;padding:8px 0}.bonus-entry{display:grid;grid-template-columns:repeat(3,minmax(0,1fr)) auto;gap:12px;align-items:end}.condition-values h4{margin:0}.sr-only{position:absolute;width:1px;height:1px;overflow:hidden;clip-path:inset(50%)}@media(max-width:720px){.bonus-entry{grid-template-columns:1fr 1fr}.bonus-entry button{grid-column:2}}@media(max-width:480px){.plan-picker,.bonus-entry{grid-template-columns:1fr}.bonus-entry button{grid-column:auto}}
</style>
