<script setup lang="ts">
import {computed,onUnmounted,ref,watch} from 'vue'
import BusinessView,{type View} from './BusinessView.vue'
import {sanitizeExchangeFile,downloadExchange} from './cloud-exchange'
import {cloudTask} from './cloud'
interface Role{ref:string;uid:string;nickname:string}
interface Account{ref:string;owner:{actor_id:string};roles:Role[]}
interface Summary{uid:string;revision:number;saved_ms:number;items:{id:string;name:string;level?:number;cons?:number}[]}
const props=defineProps<{game:string;authenticated:boolean;invoke:<T>(action:string,payload?:Record<string,unknown>)=>Promise<T>}>()
const captureCharacter=ref('')
const rankCharacter=ref(''),rankQuery=ref('all')
const accounts=ref<Account[]>([]),selected=ref(''),summary=ref<Summary|null>(null),view=ref<View|null>(null),panels=ref<{id:string;name:string;view:View}[]>([]),busy=ref(false),error=ref(''),notice=ref(''),consent=ref(false),clearing=ref(false),nextPage=ref<number|null>(null),file=ref<File|null>(null),stopping=ref(false),activeTransfer=ref('')
const transfer=cloudTask(props.invoke),choices=computed(()=>accounts.value.flatMap(a=>a.roles.map(r=>({key:JSON.stringify([a.ref,r.ref]),account:a.ref,role:r,label:`${r.nickname} · ${r.uid} · 用户 ${a.owner.actor_id}`})))),choice=computed(()=>choices.value.find(v=>v.key===selected.value))
let disposed=false
function selection(){if(!choice.value)throw new Error('请选择已授权角色。');return {account_ref:choice.value.account,role_ref:choice.value.role.ref}}
function fileChange(event:Event){file.value=(event.target as HTMLInputElement).files?.[0]??null;notice.value=''}
watch(selected,()=>{summary.value=null;view.value=null;panels.value=[];clearing.value=false;file.value=null;transfer.clear();consent.value=false})
watch(()=>props.authenticated,()=>{transfer.clear();consent.value=false})
async function run(fn:()=>Promise<void>){if(busy.value)return;busy.value=true;error.value='';notice.value='';try{await fn()}catch(e){if(!disposed)error.value=e instanceof Error?e.message:'面板交换操作未完成。'}finally{busy.value=false}}
async function accountsPage(page=0){await run(async()=>{const r=await props.invoke<{accounts:{items:Account[];next_page:number|null}}>('accounts.list',{page});accounts.value=page===0?r.accounts.items:[...accounts.value,...r.accounts.items];nextPage.value=r.accounts.next_page})}
async function load(){const result=await props.invoke<Summary>('cloud.archive.list',selection());if(!disposed){summary.value=result;if(!result.items.some(v=>v.id===rankCharacter.value))rankCharacter.value=result.items[0]?.id??''}}
async function readArchive(){await run(load)}
async function open(id:string){await run(async()=>{const result=await props.invoke<{panels:{id:string;name:string;view:View}[]}>('cloud.archive.get',{...selection(),character_id:id});panels.value=result.panels;view.value=panels.value[0]?.view??null})}
async function capture(){await run(async()=>{const result=await props.invoke<{note:string}>('cloud.archive.capture',{...selection(),character_id:captureCharacter.value.trim()});notice.value=result.note;await load()})}
async function importFile(){if(!file.value||!choice.value)return;stopping.value=false;await run(async()=>{if(file.value!.size>8*1024*1024)throw new Error('面板文件不能超过 8 MiB。');const avatars=sanitizeExchangeFile(JSON.parse(await file.value!.text()),choice.value!.role.uid,props.game);const started=await props.invoke<{ref:string}>('cloud.archive.import.start',{...selection(),uid:choice.value!.role.uid,count:avatars.length});activeTransfer.value=started.ref;try{for(let i=0;i<avatars.length;i++){if(stopping.value||disposed)throw new Error('导入已取消，原档案保留。');await props.invoke('cloud.archive.import.append',{ref:started.ref,offset:i,avatar:avatars[i]})}await props.invoke('cloud.archive.import.finish',{ref:started.ref});notice.value=`已合并 ${avatars.length} 个导入角色。`;await load()}finally{activeTransfer.value='';await props.invoke('cloud.archive.import.cancel',{ref:started.ref}).catch(()=>{})}})}
async function exportFile(){if(!choice.value)return;stopping.value=false;await run(async()=>{const started=await props.invoke<{ref:string;uid:string;total:number}>('cloud.archive.export.start',selection());activeTransfer.value=started.ref;try{const avatars:Record<string,unknown>={};for(let i=0;i<started.total;i++){if(stopping.value||disposed)throw new Error('导出已取消。');const result=await props.invoke<{avatar:Record<string,unknown>}>('cloud.archive.export.read',{ref:started.ref,offset:i});avatars[String(result.avatar.id)]=result.avatar}downloadExchange(started.uid,avatars);notice.value='已生成无凭据的交换 JSON。'}finally{activeTransfer.value='';await props.invoke('cloud.archive.export.close',{ref:started.ref}).catch(()=>{})}})}
async function remove(){await run(async()=>{await props.invoke('cloud.archive.remove',{...selection(),revision:summary.value?.revision,confirm:true});view.value=null;panels.value=[];clearing.value=false;await load();notice.value='本地交换档案已清空。'})}
async function upload(){if(!consent.value)return;await transfer.start({consent:true,authenticated:props.authenticated,...selection()},'cloud.archive.upload')}
async function download(){if(!consent.value||!choice.value)return;await transfer.start({mode:'exchange_download',uid:choice.value.role.uid,consent:true,authenticated:props.authenticated})}
async function rank(){if(!consent.value||!rankCharacter.value)return;await transfer.start({...selection(),character_id:rankCharacter.value,query:rankQuery.value,consent:true,authenticated:props.authenticated},'cloud.archive.rank')}
async function refresh(){if(!consent.value)return;await transfer.start({...selection(),consent:true,authenticated:props.authenticated},'cloud.archive.refresh')}
async function receive(){await run(async()=>{if(!summary.value)await load();await props.invoke('cloud.archive.receive',{...selection(),ref:transfer.job.value?.ref,revision:summary.value?.revision,confirm:true});await load();notice.value='已合并下载的角色，来源为第三方交换档案。'})}
onUnmounted(()=>{disposed=true;stopping.value=true;transfer.dispose();if(activeTransfer.value)void props.invoke('cloud.archive.import.cancel',{ref:activeTransfer.value}).catch(()=>{})})
</script>
<template>
 <details class="cloud-exchange"><summary>面板交换档案 · 导入、导出与云交换</summary><div class="exchange-content"><p class="hint">保存 miao PlayerData 格式的第三方/导入面板。仅可为已授权的相同 UID 建立档案，来源与官方面板分开。云上传会发送 UID 和全部交换角色；接收窗口由 ark 提供，有效十分钟。</p>
 <p v-if="error||transfer.error.value" role="alert" class="feedback danger">{{error||transfer.error.value}}</p><p v-if="notice" role="status">{{notice}}</p>
 <div class="actions"><button :disabled="busy" @click="accountsPage()">读取可用交换账号</button><button v-if="nextPage!==null" :disabled="busy" @click="accountsPage(nextPage!)">更多交换账号</button></div>
 <label v-if="choices.length">交换档案账号<select v-model="selected" :disabled="busy||transfer.job.value?.state==='running'"><option value="" disabled>选择已授权角色</option><option v-for="c in choices" :key="c.key" :value="c.key">{{c.label}}</option></select></label>
 <template v-if="choice"><div class="actions"><button :disabled="busy" @click="readArchive">读取本地交换档案</button><button :disabled="busy||!summary?.items.length" @click="exportFile">导出交换 JSON</button><button :disabled="busy||!summary?.items.length" @click="clearing=true">清空交换档案</button></div>
 <form @submit.prevent="capture"><fieldset :disabled="busy"><legend>从本人官方面板建立交换副本</legend><label>读取官方面板的角色名称或 ID<input v-model="captureCharacter" required></label><p class="hint">角色与装备按固定资料转为 miao 交换格式。强化档位根据官方显示值还原，存在舍入误差；只在本地保存。</p><button :disabled="!captureCharacter">读取并保存官方面板</button></fieldset></form>
 <form @submit.prevent="importFile"><fieldset :disabled="busy"><legend>导入本人面板文件</legend><label>miao PlayerData JSON<input type="file" accept="application/json,.json" @change="fileChange"></label><p class="hint">浏览器仅提交角色业务字段，未知和凭据字段不上传。同一角色会被文件中的数据替换，其他已保存角色保留。</p><button :disabled="!file">筛选并导入面板文件</button></fieldset></form><button v-if="activeTransfer" @click="stopping=true">停止后续传输</button>
 <section v-if="clearing" class="feedback"><p>清空此账号全部本地交换角色？</p><div class="actions"><button :disabled="busy" @click="clearing=false">保留交换档案</button><button class="destructive" :disabled="busy" @click="remove">确认清空交换档案</button></div></section>
 <p v-if="summary" class="hint">已保存 {{summary.items.length}} 个角色。<template v-if="summary.saved_ms">最近保存 {{new Date(summary.saved_ms).toLocaleString()}}</template></p><ul v-if="summary?.items.length"><li v-for="item in summary.items" :key="item.id"><button :disabled="busy" @click="open(item.id)">{{item.name||item.id}} · 等级 {{item.level??'未提供'}}</button></li></ul><BusinessView v-if="view" :value="view"/>
 <fieldset :disabled="busy||transfer.busy.value||transfer.job.value?.state==='running'"><legend>十分钟云交换</legend><label class="check"><input v-model="consent" type="checkbox">同意向 ark 发送所选 UID，并在上传或排名时发送所选交换角色的业务数据</label><div class="actions"><button :disabled="!consent||!summary?.items.length" @click="upload">上传此交换档案</button><button :disabled="!consent" @click="download">下载此 UID 的交换档案</button><button :disabled="!consent" @click="refresh">请求更新云面板</button></div><template v-if="summary?.items.length"><label>本地面板排名角色<select v-model="rankCharacter"><option v-for="item in summary.items" :key="item.id" :value="item.id">{{item.name||item.id}}</option></select></label><label>本地面板排名类别<select v-model="rankQuery"><option value="all">伤害与装备分别计算</option><option value="dmg">伤害</option><option value="mark">装备评分</option></select></label><button :disabled="!consent||!rankCharacter" @click="rank">查询所选导入面板的云排名</button></template></fieldset>
 <div v-if="transfer.job.value?.state==='running'" role="status">云交换处理中。<button @click="transfer.cancel">取消云交换</button></div><p v-if="transfer.job.value?.state==='failed'" role="alert">{{transfer.job.value.message}}</p><BusinessView v-if="transfer.job.value?.view" :value="transfer.job.value.view"/><button v-if="transfer.job.value?.state==='completed'&&transfer.job.value.exchange?.direction==='downloaded'" :disabled="busy" @click="receive">将下载结果合并到本地交换档案</button>
 </template></div></details>
</template>
<style scoped>.cloud-exchange{border-top:1px solid var(--raylea-color-border);padding-top:20px}.cloud-exchange summary{font-weight:600;cursor:pointer}.exchange-content{display:grid;gap:16px;margin-top:16px}.cloud-exchange label:not(.check){display:grid;gap:8px;min-width:0}.cloud-exchange select{min-width:0;width:100%}.cloud-exchange fieldset{display:grid;gap:14px;min-width:0;border:1px solid var(--raylea-color-border);border-radius:12px;padding:16px}.cloud-exchange ul{display:flex;gap:10px;flex-wrap:wrap;list-style:none;padding:0;margin:0}</style>
