type ObjectMap=Record<string,unknown>
function object(value:unknown):ObjectMap {if(!value||typeof value!=='object'||Array.isArray(value))throw new Error('面板对象格式无效。');return value as ObjectMap}
function pick(source:ObjectMap,keys:string[]){const result:ObjectMap={};for(const key of keys)if(Object.hasOwn(source,key))result[key]=source[key];return result}
function gear(value:unknown){const raw=object(value),out=pick(raw,['id','name','star','level','mainId']);if(raw.attrIds!==undefined){if(!Array.isArray(raw.attrIds)||raw.attrIds.length>32)throw new Error('装备副词条数量无效。');out.attrIds=raw.attrIds.map(v=>v&&typeof v==='object'?pick(object(v),['id','count','step']):v)}return out}
export function sanitizeExchangeFile(value:unknown,uid:string,game:string):ObjectMap[]{
 const data=object(value);if(String(data.uid)!==uid)throw new Error('文件 UID 与所选已授权角色不一致。');const avatars=Array.isArray(data.avatars)?data.avatars:Object.values(object(data.avatars));if(!avatars.length||avatars.length>250)throw new Error('请选择包含 1–250 个角色的 miao PlayerData JSON。')
 const seen=new Set<string>();return avatars.map(value=>{const raw=object(value),id=String(raw.id);if(!/^\d{1,9}$/.test(id)||seen.has(id)||Number(id)<1||(game==='genshin'?Number(id)<10000000:Number(id)>=10000000))throw new Error('角色编号重复或与所选游戏不一致。');seen.add(id);const out=pick(raw,['id','name','elem','level','promote','cons','fetter','costume','_time','_update','_talent']);out._source='share';if(Object.hasOwn(raw,'weapon')&&raw.weapon===null)out.weapon=null;if(raw.weapon!=null)out.weapon=pick(object(raw.weapon),['id','name','level','promote','affix']);if(raw.talent!==undefined){const talents=object(raw.talent),safe:ObjectMap={};for(const [key,v]of Object.entries(talents)){if(!'a a2 a3 e e1 e2 e3 q q2 q3 t t2 z xe xe2 me me2 mt mt1 mt2'.split(' ').includes(key))continue;safe[key]=v&&typeof v==='object'?object(v).level:v}out.talent=safe}if(raw.trees!==undefined){if(!Array.isArray(raw.trees)||raw.trees.length>128||raw.trees.some(v=>!/^\w[\w-]{0,31}$/.test(String(v))))throw new Error('行迹列表无效。');out.trees=raw.trees}
 for(const field of ['artis','mysArtis'])if(raw[field]!==undefined){const slots=object(raw[field]),safe:ObjectMap={};for(const [key,v]of Object.entries(slots)){const slot=key.replace(/^arti/,'');if(!/^[1-6]$/.test(slot)||game==='genshin'&&slot==='6'||Object.hasOwn(safe,slot))throw new Error('装备部位无效或重复。');safe[slot]=gear(v)}out[field]=safe}
 const serialized=JSON.stringify(out);if(new TextEncoder().encode(serialized).length>32768)throw new Error('单角色面板超过 32 KiB。');return out})
}
export function downloadExchange(uid:string,avatars:Record<string,unknown>){const blob=new Blob([JSON.stringify({uid,avatars},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`player-${uid}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
