<script setup lang="ts">
import{ref,watch}from'vue'
import BusinessView,{type View}from'./BusinessView.vue'
const props=defineProps<{invoke:<T>(action:string,payload?:Record<string,unknown>)=>Promise<T>;roles:{key:string;label:string;role:{ref:string};account:{ref:string}}[]}>()
const selected=ref(''),busy=ref(false),error=ref(''),view=ref<View|null>(null),birthdays=ref<{role_id:string;name:string;image_url?:string}[]>([]),claiming=ref(''),groups=ref<{scope:Record<string,string>}[]>([]),group=ref(''),members=ref<{actor_id:string;nickname:string;uid:string;saved_ms:number;cards:{name:string;count:number;unlocked:boolean}[]}[]>([]),removeActor=ref('')
function choice(){const r=props.roles.find(v=>v.key===selected.value);if(!r)throw Error('请选择已授权角色。');return {account_ref:r.account.ref,role_ref:r.role.ref}}
async function run(work:()=>Promise<void>){if(busy.value)return;busy.value=true;error.value='';try{await work()}catch(e){error.value=e instanceof Error?e.message:'收藏操作未完成。'}finally{busy.value=false}}
async function birthday(){await run(async()=>{view.value=null;birthdays.value=[];claiming.value='';const r=await props.invoke<{view:View;data:{items:typeof birthdays.value}}>('birthday.list',choice());view.value=r.view;birthdays.value=r.data.items})}
async function cards(){await run(async()=>{view.value=(await props.invoke<{view:View}>('cards.query',choice())).view})}
async function loadGroups(){await run(async()=>{let page=0;groups.value=[];while(true){const r=await props.invoke<{items:{scope:Record<string,string>}[];next_page:number|null}>('groups.list',{page});groups.value.push(...r.items);if(r.next_page===null||r.next_page<=page)break;page=r.next_page;if(page>100)break}})}
async function loadMembers(){members.value=(await props.invoke<{items:typeof members.value}>('cards.group.list',{scope:JSON.parse(group.value)})).items;removeActor.value=''}
watch(selected,()=>{view.value=null;birthdays.value=[];claiming.value=''});watch(group,()=>{members.value=[];removeActor.value=''})
</script>
<template><section><h2>生日留影与月谕圣牌</h2><label>原神角色<select v-model="selected" :disabled="busy"><option value="">选择本人授权角色</option><option v-for="r in roles" :key="r.key" :value="r.key">{{r.label}}</option></select></label><div class="actions"><button :disabled="busy||!selected" @click="birthday">查询生日留影</button><button :disabled="busy||!selected" @click="cards">查询圣牌收藏</button></div><p v-if="error" role="alert" class="feedback danger">{{error}}</p><BusinessView v-if="view" :value="view"/><ul><li v-for="b in birthdays" :key="b.role_id"><strong>{{b.name}}</strong> <a v-if="b.image_url" :href="b.image_url" target="_blank" rel="noreferrer">官方留影图片</a><button :disabled="busy" @click="claiming=b.role_id">领取此生日留影</button><div v-if="claiming===b.role_id" class="actions"><span>确认为所选账号领取 {{b.name}} 的生日留影？</span><button :disabled="busy" @click="run(async()=>{view=(await invoke<{view:View}>('birthday.claim',{...choice(),role_id:b.role_id,confirm:true})).view;claiming=''})">确认领取</button><button :disabled="busy" @click="claiming=''">取消</button></div></li></ul><p>圣牌交换只匹配愿意互相交换的群成员。在目标群发送“原神圣牌提交”加入，“原神圣牌交换”查看双向匹配，“原神圣牌退出”撤回。记录保留30天，插件不自动赠送卡片。</p></section>
<section><div class="section-heading"><h2>群圣牌交换记录</h2><button :disabled="busy" @click="loadGroups">读取已保存群</button></div><form @submit.prevent="run(loadMembers)"><label>目标群<select v-model="group" :disabled="busy" required><option value="">选择群</option><option v-for="g in groups" :key="JSON.stringify(g.scope)" :value="JSON.stringify(g.scope)">{{g.scope.source_adapter}} / {{g.scope.bot_id}} / {{g.scope.group_id}}</option></select></label><button :disabled="busy||!group">读取交换记录</button></form><ul><li v-for="m in members" :key="m.actor_id"><strong>{{m.nickname||m.actor_id}}</strong> · {{m.actor_id}} · {{m.uid}}<p>{{new Date(m.saved_ms).toLocaleString()}} 更新 · {{m.cards.length}} 种圣牌</p><button :disabled="busy" @click="removeActor=m.actor_id">移除此交换记录</button><div v-if="removeActor===m.actor_id" class="actions"><span>确认移除此成员的群交换记录？</span><button :disabled="busy" @click="run(async()=>{await invoke('cards.group.remove',{scope:JSON.parse(group),actor_id:m.actor_id,confirm:true});await loadMembers()})">确认移除记录</button><button :disabled="busy" @click="removeActor=''">取消</button></div></li></ul></section></template>
<style scoped>section{display:grid;gap:16px}label{display:grid;gap:8px;min-width:0}select{width:100%;min-width:0}ul{padding:0;list-style:none;display:grid;gap:16px}li{display:grid;gap:10px;border-bottom:1px solid var(--raylea-color-border);padding-block:12px;overflow-wrap:anywhere}form{display:grid;gap:12px}</style>
