<script setup lang="ts">
import{onUnmounted,ref}from'vue'
import{uploadMedia,readMedia,type MediaEntry,type MediaInvoke}from'./media'
const props=defineProps<{invoke:MediaInvoke;prefix:string}>()
const labels:Record<string,string>={character:'角色图鉴',weapon:'装备',food:'食物',enemy:'怪物',domain:'秘境',artifact:'套装',material:'材料',guide:'攻略',birthday:'生日',photo:'角色照片',other:'其他'}
const items=ref<MediaEntry[]>([]),total=ref(0),totalBytes=ref(0),next=ref<number|null>(null),query=ref(''),filter=ref(''),category=ref('photo'),catalogID=ref(''),source=ref(''),license=ref('本人有权使用'),rights=ref(false),files=ref<File[]>([]),busy=ref(false),error=ref(''),notice=ref(''),progress=ref(''),preview=ref(''),selected=ref<MediaEntry|null>(null),editing=ref<MediaEntry|null>(null),removeRef=ref(''),catalogQuery=ref(''),entries=ref<{id:string;name:string}[]>([])
let controller:AbortController|undefined,disposed=false
async function run(work:()=>Promise<void>){if(busy.value)return;busy.value=true;error.value='';notice.value='';try{await work()}catch(e){error.value=e instanceof Error?e.message:'图库操作未完成。'}finally{busy.value=false;progress.value=''}}
async function list(offset=0){const r=await props.invoke<{items:MediaEntry[];total:number;total_bytes:number;next_offset:number|null}>('media.list',{query:query.value,category:filter.value,offset});items.value=offset?[...items.value,...r.items]:r.items;total.value=r.total;totalBytes.value=r.total_bytes;next.value=r.next_offset}
function choose(event:Event){files.value=Array.from((event.target as HTMLInputElement).files??[]).filter(f=>/\.(png|jpe?g|gif|webp)$/i.test(f.name));rights.value=false}
async function upload(){if(!rights.value||!files.value.length)return;await run(async()=>{controller=new AbortController();let done=0;const pending=[...files.value];for(const file of pending){if(disposed||controller.signal.aborted)break;progress.value=`第 ${done+1} / ${pending.length} 张：${file.name}`;await uploadMedia(props.invoke,file,{title:file.name.replace(/\.[^.]+$/,''),category:category.value,catalog_id:catalogID.value,source:source.value,license:license.value},controller.signal,bytes=>{progress.value=`第 ${done+1} / ${pending.length} 张 · ${Math.round(bytes/file.size*100)}%`});done++;files.value=files.value.filter(f=>f!==file)}if(!disposed){notice.value=`已导入 ${done} 张。${files.value.length?'剩余文件可以继续导入。':''}`;await list()}});controller=undefined}
function clearPreview(){if(preview.value)URL.revokeObjectURL(preview.value);preview.value='';selected.value=null;editing.value=null}
async function show(entry:MediaEntry){await run(async()=>{clearPreview();controller=new AbortController();const r=await readMedia(props.invoke,entry.ref,controller.signal);if(disposed)return;preview.value=URL.createObjectURL(r.blob);selected.value=r.entry;editing.value={...r.entry}});controller=undefined}
async function save(){if(!editing.value)return;await run(async()=>{const r=await props.invoke<{entry:MediaEntry}>('media.update',editing.value as unknown as Record<string,unknown>);selected.value=r.entry;editing.value={...r.entry};await list();notice.value='素材信息已保存。'})}
async function remove(entry:MediaEntry){await run(async()=>{await props.invoke('media.remove',{ref:entry.ref,revision:entry.revision,confirm:true});if(selected.value?.ref===entry.ref)clearPreview();removeRef.value='';await list();notice.value='素材已删除。'})}
async function findCatalog(){await run(async()=>{entries.value=(await props.invoke<{entries:{id:string;name:string}[]}>('catalog.search',{query:catalogQuery.value})).entries})}
void run(()=>list());onUnmounted(()=>{disposed=true;controller?.abort();clearPreview()})
</script>
<template><section class="media-library"><div class="section-heading"><h2>本地图库</h2><span>{{total}} 项匹配 · 全库 {{(totalBytes/1024/1024).toFixed(1)}} MiB</span></div><p>只保存你导入的素材。原图支持 PNG、JPEG、GIF、WebP，每张4 MiB、2400万像素；全库最多2000项、512 MiB。</p><form class="query-form" @submit.prevent="run(()=>list())"><label>搜索素材<input v-model="query" :disabled="busy"></label><label>筛选分类<select v-model="filter" :disabled="busy"><option value="">全部分类</option><option v-for="(label,key) in labels" :key="key" :value="key">{{label}}</option></select></label><button :disabled="busy">查询图库</button></form><p v-if="error" role="alert" class="feedback danger">{{error}}</p><p v-if="notice" role="status" class="feedback">{{notice}}</p><p v-if="progress" role="status">{{progress}} <button type="button" @click="controller?.abort()">停止上传</button></p>
<details><summary>导入图片或资源目录</summary><div class="query-form"><label>选择图片<input type="file" accept="image/png,image/jpeg,image/gif,image/webp" multiple :disabled="busy" @change="choose"></label><label>选择目录<input type="file" webkitdirectory multiple :disabled="busy" @change="choose"></label><label>素材分类<select v-model="category" :disabled="busy"><option v-for="(label,key) in labels" :key="key" :value="key">{{label}}</option></select></label><label>来源或作者<input v-model="source" maxlength="512" :disabled="busy" placeholder="原作者或你自己的素材"></label><label>使用许可<input v-model="license" maxlength="256" :disabled="busy" required></label><label>查找关联角色/装备<input v-model="catalogQuery" :disabled="busy"></label><button type="button" :disabled="busy" @click="findCatalog">查找资料条目</button><label>关联条目<select v-model="catalogID" :disabled="busy"><option value="">不关联</option><option v-for="entry in entries" :key="entry.id" :value="entry.id">{{entry.name}} · {{entry.id}}</option></select></label></div><p>已选 {{files.length}} 张图片，非图片文件自动忽略。批量导入使用相同分类与关联条目，之后可逐项修改。</p><label class="check"><input v-model="rights" type="checkbox" :disabled="busy">确认我有权在此机器人中使用这些素材</label><button :disabled="busy||!rights||!files.length||!license.trim()" @click="upload">导入所选图片</button></details>
<p v-if="!items.length" class="empty">没有匹配素材。导入并关联角色后，可以发送“{{prefix}}照片 角色名”。</p><ul class="media-list"><li v-for="entry in items" :key="entry.ref"><div><strong>{{entry.title}}</strong><span>{{labels[entry.category]}} · {{entry.width}}×{{entry.height}} · {{(entry.bytes/1024).toFixed(0)}} KiB</span></div><div class="actions"><button :disabled="busy" @click="show(entry)">查看与编辑</button><button :disabled="busy" @click="removeRef=entry.ref">删除</button></div><div v-if="removeRef===entry.ref" class="actions"><span>确认删除此素材原图？</span><button :disabled="busy" @click="remove(entry)">确认删除</button><button :disabled="busy" @click="removeRef=''">取消</button></div></li></ul><button v-if="next!==null" :disabled="busy" @click="run(()=>list(next!))">更多素材</button>
<article v-if="selected&&editing"><div class="section-heading"><h3>{{selected.title}}</h3><button :disabled="busy" @click="clearPreview">关闭预览</button></div><img class="media-preview" :src="preview" :alt="selected.title"><p><a :href="preview" :download="selected.title+'.'+selected.mime.split('/')[1]">下载原图</a></p><form class="query-form" @submit.prevent="save"><label>标题<input v-model="editing.title" maxlength="120" :disabled="busy" required></label><label>分类<select v-model="editing.category" :disabled="busy"><option v-for="(label,key) in labels" :key="key" :value="key">{{label}}</option></select></label><label>关联条目 ID<input v-model="editing.catalog_id" :disabled="busy"></label><label>来源<input v-model="editing.source" maxlength="512" :disabled="busy"></label><label>使用许可<input v-model="editing.license" maxlength="256" :disabled="busy" required></label><button :disabled="busy">保存素材信息</button></form></article></section></template>
<style scoped>.media-library{display:grid;gap:16px}.media-list{padding:0;list-style:none;display:grid;gap:16px}.media-list li{padding-block:12px;border-bottom:1px solid var(--raylea-color-border);display:flex;gap:12px;flex-wrap:wrap;justify-content:space-between}.media-list li>div:first-child{display:grid;gap:6px;overflow-wrap:anywhere;min-width:0}.media-preview{max-width:100%;max-height:600px;object-fit:contain}.media-library label:not(.check){display:grid;gap:8px;min-width:0}.media-library input,.media-library select{min-width:0;width:100%}.media-library .check input{width:auto}.media-library details>div{margin-block:16px}</style>
