export interface MediaEntry {ref:string;revision:number;title:string;category:string;catalog_id:string;source:string;license:string;mime:string;bytes:number;width:number;height:number;created_ms:number}
export type MediaInvoke=<T>(action:string,payload?:Record<string,unknown>)=>Promise<T>
export async function uploadMedia(invoke:MediaInvoke,file:File,metadata:Record<string,unknown>,signal:AbortSignal,onProgress:(done:number)=>void){
 if(file.size<12||file.size>4*1024*1024)throw Error('每张图片应不超过4 MiB。')
 const bitmap=await createImageBitmap(file);try{if(bitmap.width*bitmap.height>24000000)throw Error('图片超过2400万像素。')}finally{bitmap.close()}
 if(signal.aborted)throw Error('上传已停止。')
 const {ref}=await invoke<{ref:string}>('media.upload.start',{...metadata,size:file.size,rights_confirmed:true})
 try{const bytes=new Uint8Array(await file.arrayBuffer());for(let offset=0;offset<bytes.length;offset+=49152){if(signal.aborted)throw Error('上传已停止。');const chunk=bytes.subarray(offset,offset+49152);let binary='';for(const b of chunk)binary+=String.fromCharCode(b);const r=await invoke<{offset:number}>('media.upload.append',{ref,offset,data:btoa(binary)});if(r.offset!==offset+chunk.length)throw Error('上传进度不一致，请重试。');onProgress(r.offset)}if(signal.aborted)throw Error('上传已停止。');return(await invoke<{entry:MediaEntry}>('media.upload.finish',{ref})).entry}catch(e){await invoke('media.upload.cancel',{ref}).catch(()=>{});throw e}
}
export async function readMedia(invoke:MediaInvoke,ref:string,signal:AbortSignal){let offset=0,entry:MediaEntry|undefined;const parts:Uint8Array<ArrayBuffer>[]=[];while(true){if(signal.aborted)throw Error('原图读取已停止。');const r=await invoke<{entry:MediaEntry;data:string;offset:number;more:boolean}>('media.read',{ref,offset});if(!entry)entry=r.entry;if(entry.ref!==ref||entry.bytes!==r.entry.bytes||entry.bytes>4*1024*1024)throw Error('原图数据已变化。');const decoded=atob(r.data),bytes=new Uint8Array(decoded.length);for(let i=0;i<decoded.length;i++)bytes[i]=decoded.charCodeAt(i);if(r.offset!==offset+bytes.length||r.offset>entry.bytes||r.more&&bytes.length===0)throw Error('原图分块无效。');parts.push(bytes);offset=r.offset;if(!r.more){if(offset!==entry.bytes)throw Error('原图未读取完整。');return {entry,blob:new Blob(parts,{type:entry.mime})}}}}
