<script setup lang="ts">
import{ref,watch}from'vue'
const props=defineProps<{invoke:<T>(action:string,payload?:Record<string,unknown>)=>Promise<T>;roles:{key:string;label:string;role:{ref:string};account:{ref:string}}[]}>()
const selected=ref(''),actions=ref<string[]>([]),action=ref(''),days=ref<{date:string;estimated_minutes:number;periods:[number,number][]}[]>([]),note=ref(''),busy=ref(false),error=ref('')
watch(selected,()=>{actions.value=[];action.value='';days.value=[];note.value=''})
function time(n:number){return String(Math.floor(n/60)).padStart(2,'0')+':'+String(n%60).padStart(2,'0')}
async function load(calculate=false){busy.value=true;error.value='';try{const role=props.roles.find(r=>r.key===selected.value);if(!role)throw Error('请选择角色。');const r=await props.invoke<{actions:string[];days:typeof days.value;note?:string}>('billing.playtime',{account_ref:role.account.ref,role_ref:role.role.ref,recovery_action:calculate?action.value:''});actions.value=r.actions;days.value=r.days;note.value=r.note??''}catch(e){error.value=e instanceof Error?e.message:'估算未完成。'}finally{busy.value=false}}
</script>
<template><section><h2>在线时长估算</h2><p>先在上方收集“开拓力 · 全部变动”的官方资产记录，再选择自然恢复记录分类。此功能根据恢复节奏推算，无法证明实际在线或离线。</p><form class="query-form" @submit.prevent="load()"><label>星铁角色<select v-model="selected" :disabled="busy"><option value="">选择角色</option><option v-for="r in roles" :key="r.key" :value="r.key">{{r.label}}</option></select></label><button :disabled="busy||!selected">读取开拓力记录分类</button></form><form v-if="actions.length" class="query-form" @submit.prevent="load(true)"><label>自然恢复分类<select v-model="action" :disabled="busy"><option value="">选择自然恢复分类</option><option v-for="name in actions" :key="name" :value="name">{{name}}</option></select></label><button :disabled="busy||!action">估算时长</button></form><p v-if="error" class="feedback danger" role="alert">{{error}}</p><p v-if="note">{{note}}</p><ul><li v-for="d in days" :key="d.date"><strong>{{d.date}}</strong> · 约{{(d.estimated_minutes/60).toFixed(1)}}小时<p>{{d.periods.map(p=>time(p[0])+'–'+time(p[1])).join('、')}}</p></li></ul></section></template>
