<script setup lang="ts">
import {computed,onUnmounted,ref,watch} from 'vue'
import {cloudTask} from './cloud'
const props=defineProps<{prefix:string;invoke:<T>(action:string,payload?:Record<string,unknown>)=>Promise<T>}>()
interface Post{id:string;title:string;url:string;created:string;author?:string;parts?:string[];images?:string[]}
interface Activity{id:string;title:string;text:string;start?:string;end?:string;time_status:string}
interface Subscription{ref:string;group_id:string;kinds:string[];last_code?:string}
const task=cloudTask(props.invoke,'content'),kind=ref('news'),type=ref(1),query=ref(''),postID=ref(''),part=ref(0),selected=ref(''),date=ref(''),subscriptions=ref<Subscription[]>([]),subError=ref(''),subBusy=ref(false),removeRef=ref('')
const result=computed(()=>task.job.value?.result),posts=computed(()=>(result.value?.items??[]) as Post[]),post=computed(()=>result.value?.post as Post|undefined),activities=computed(()=>((result.value?.items??[]) as Activity[]).filter(v=>!date.value||v.start&&v.end&&v.start.slice(0,10)<=date.value&&v.end.slice(0,10)>=date.value)),detail=computed(()=>activities.value.find(a=>a.id===selected.value))
watch([kind,type,query,postID],()=>{task.clear();selected.value='';part.value=0})
async function start(next=false){selected.value='';part.value=0;const previous=result.value;await task.start({kind:kind.value,type:type.value,query:query.value.trim(),post_id:postID.value.trim(),last_id:next?previous?.next_id??'':'',offset:next?previous?.next_offset??0:0})}
async function loadSubscriptions(){subBusy.value=true;subError.value='';try{subscriptions.value=(await props.invoke<{items:Subscription[]}>('content.subscription.list')).items}catch(e){subError.value=e instanceof Error?e.message:'推送列表读取失败。'}finally{subBusy.value=false}}
async function remove(){subBusy.value=true;subError.value='';try{await props.invoke('content.subscription.remove',{ref:removeRef.value,confirm:true});removeRef.value='';await loadSubscriptions()}catch(e){subError.value=e instanceof Error?e.message:'移除未完成。'}finally{subBusy.value=false}}
void loadSubscriptions();onUnmounted(task.dispose)
</script>
<template><section class="public-content"><h2>官方公告与活动</h2><p>匿名读取官方公开内容。活动时间未确定时保留公告原文；时间按国服显示。</p><form class="query-form" @submit.prevent="start()"><label>查询内容<select v-model="kind"><option value="news">公告、资讯与活动帖子</option><option value="calendar">活动日历与游戏公告</option><option value="search">米游社搜索</option><option value="estimate">版本资源预估与盘点</option><option value="post">文章详情与原图链接</option></select></label><label v-if="kind==='news'">帖子类型<select v-model="type"><option :value="1">公告</option><option :value="2">活动</option><option :value="3">资讯</option></select></label><label v-if="kind==='search'">搜索关键词<input v-model="query" maxlength="100" required></label><label v-if="kind==='post'">文章编号或官方链接<input v-model="postID" required></label><button :disabled="task.busy.value||task.job.value?.state==='running'">查询公开内容</button></form><p v-if="task.error.value||task.job.value?.message" role="alert" class="feedback danger">{{task.error.value||task.job.value?.message}}</p><p v-if="task.job.value?.state==='running'">正在读取… <button @click="task.cancel">取消</button><button @click="task.poll">刷新进度</button></p>
<template v-if="task.job.value?.state==='completed'"><p v-if="result?.note" class="hint">{{result.note}}</p><p class="hint">获取时间：{{new Date(Number(result?.fetched_at_ms)).toLocaleString()}}</p>
<template v-if="kind==='news'||kind==='search'||kind==='estimate'"><p v-if="!posts.length" class="empty">没有匹配帖子。</p><ol class="post-list"><li v-for="p in posts" :key="p.id"><strong>{{p.title}}</strong><span>{{p.created}} {{p.author}}</span><div class="actions"><button @click="kind='post';postID=p.id">填入文章详情</button><a :href="p.url" target="_blank" rel="noreferrer">官方原文</a></div></li></ol><button v-if="result?.more" @click="start(true)">下一页帖子</button></template>
<template v-if="kind==='post'&&post"><h3>{{post.title}}</h3><p>{{post.author}} {{post.created}} <a :href="post.url" target="_blank" rel="noreferrer">官方原文</a></p><div class="actions"><button :disabled="part<=0" @click="part--">上一段</button><span>{{part+1}} / {{Math.max(1,post.parts?.length??0)}}</span><button :disabled="part+1>=(post.parts?.length??0)" @click="part++">下一段</button></div><p class="prose">{{post.parts?.[part]||'本文主要内容为图片或视频，请查看官方原文。'}}</p><ol><li v-for="(url,i) in post.images" :key="url"><a :href="url" target="_blank" rel="noreferrer">查看官方原图 {{i+1}}</a></li></ol></template>
<template v-if="kind==='calendar'"><label>查看覆盖日期（留空含时间未确定项）<input v-model="date" type="date"></label><div class="calendar-list"><button v-for="v in activities" :key="v.id" @click="selected=v.id"><strong>{{v.title}}</strong><span>{{v.end?(v.start||'开始时间未确定')+' 至 '+v.end:'活动时间未确定 · 可查看公告'}}</span></button></div><p v-if="!activities.length" class="empty">此范围没有可确认活动。</p><article v-if="detail"><h3>{{detail.title}}</h3><p class="prose">{{detail.text}}</p></article></template></template></section>
<section><div class="section-heading"><h2>群推送</h2><button :disabled="subBusy" @click="loadSubscriptions">刷新</button></div><p>群管理员在群里发送“{{prefix}}开启公告推送”或“{{prefix}}开启资讯推送”开启，“开启”换成“关闭”即停止。每五分钟推送两小时内的一条新帖；超级管理员发送“{{prefix}}推送公告”立即检查。</p><p v-if="subError" role="alert" class="feedback danger">{{subError}}</p><p v-if="!subscriptions.length" class="empty">没有开启推送的群。</p><ul class="post-list"><li v-for="s in subscriptions" :key="s.ref"><strong>群 {{s.group_id}} · {{s.kinds.map(k=>({announce:'公告',info:'资讯'} as Record<string,string>)[k]).join('、')}}</strong><span>{{s.last_code||'等待首次检查'}}</span><button :disabled="subBusy" @click="removeRef=s.ref">移除此群的推送</button><div v-if="removeRef===s.ref" class="actions"><span>确认停止此群的全部推送？</span><button :disabled="subBusy" @click="remove">确认移除</button><button :disabled="subBusy" @click="removeRef=''">取消</button></div></li></ul></section></template>
<style scoped>.public-content{display:grid;gap:16px}.post-list{padding:0;list-style:none;display:grid;gap:16px}.post-list li{display:grid;gap:8px;padding-block:12px;border-bottom:1px solid var(--raylea-color-border)}.calendar-list{display:grid;gap:8px}.calendar-list button{display:grid;gap:8px;text-align:left;white-space:normal;overflow-wrap:anywhere}.prose{white-space:pre-wrap;overflow-wrap:anywhere}label{display:grid;gap:8px;min-width:0}input,select{min-width:0}</style>
