<script setup lang="ts">
import{computed,onUnmounted,ref,watch}from'vue'
import{cloudTask}from'./cloud'
interface Row{name:string;id:string;tier?:string;use_rate?:number|null;holding_rate?:number|null;sample?:number|null;level?:number|null;average_constellation?:number|null;constellations:(number|null)[]}
interface Team{names:string[];up:number|null;middle:number|null;down:number|null;use_rate:number|null}
interface Pair{up:{team:Team;owned:boolean;fallback:boolean};down:{team:Team;owned:boolean;fallback:boolean};weight:number}
const props=defineProps<{invoke:<T>(action:string,payload?:Record<string,unknown>)=>Promise<T>;roles:{key:string;label:string;account:{ref:string};role:{ref:string}}[]}>()
const task=cloudTask(props.invoke,'content'),source=ref('ownership'),query=ref(''),offset=ref(0),selection=ref(''),busy=ref(false),error=ref(''),pairs=ref<Pair[]>([]),note=ref('')
const result=computed(()=>task.job.value?.result),rows=computed(()=>((result.value?.rows??[])as Row[]).filter(v=>!query.value||v.name.includes(query.value))),teams=computed(()=>(result.value?.teams??[])as Team[]),meta=computed(()=>(result.value?.meta??{}) as Record<string,unknown>)
function n(v:number|null|undefined,suffix=''){return v==null?'未提供':v.toLocaleString(undefined,{maximumFractionDigits:2})+suffix}
watch(source,()=>{task.clear();offset.value=0;pairs.value=[];note.value=''});watch(query,()=>offset.value=0)
async function compare(){if(!task.job.value)return;busy.value=true;error.value='';pairs.value=[];try{const role=props.roles.find(v=>v.key===selection.value);if(!role)throw Error('请选择本人角色。');const r=await props.invoke<{pairs:Pair[];note:string}>('statistics.teams',{ref:task.job.value.ref,account_ref:role.account.ref,role_ref:role.role.ref});pairs.value=r.pairs;note.value=r.note}catch(e){error.value=e instanceof Error?e.message:'本人配队匹配未完成。'}finally{busy.value=false}}
onUnmounted(task.dispose)
</script>
<template><section><h2>原神公开样本统计</h2><p>持有率与命座分布来自不同数据源，样本不等于全体玩家；缺失数值保留“未提供”。</p><form class="query-form" @submit.prevent="task.start({kind:'stats',source})"><label>数据来源与内容<select v-model="source"><option value="ownership">Lelaer命座与Yshelper持有率</option><option value="abyss">Yshelper深渊使用率与队伍</option><option value="stygian">Lelaer幽境使用率与队伍</option></select></label><button :disabled="task.busy.value||task.job.value?.state==='running'">查询公开统计</button></form><p v-if="task.error.value||task.job.value?.message" class="feedback danger" role="alert">{{task.error.value||task.job.value?.message}}</p><p v-if="task.job.value?.state==='running'">正在读取… <button @click="task.cancel">取消</button><button @click="task.poll">刷新进度</button></p><template v-if="task.job.value?.state==='completed'"><h3>{{meta.title}}</h3><p>数据版本 {{meta.version??'未提供'}} · 更新 {{meta.last_update??'未提供'}} · {{result?.source}}</p><p v-if="meta.holding_source_available===false" class="feedback attention">持有率来源暂不可用；命座分布已保留。</p><label>筛选角色<input v-model="query"></label><div class="table-scroll"><table><thead><tr><th>角色</th><th>分组</th><th>使用率</th><th>持有率</th><th>样本数</th><th>平均等级/命座</th><th>0–6命分布</th></tr></thead><tbody><tr v-for="v in rows.slice(offset,offset+50)" :key="v.name"><td>{{v.name}}</td><td>{{v.tier||'—'}}</td><td>{{n(v.use_rate,'%')}}</td><td>{{n(v.holding_rate,'%')}}</td><td>{{n(v.sample)}}</td><td>{{n(v.level)}} / {{n(v.average_constellation)}}</td><td>{{v.constellations.map(v=>n(v,'%')).join(' / ')}}</td></tr></tbody></table></div><div class="actions"><button :disabled="offset===0" @click="offset=Math.max(0,offset-50)">上一页</button><span>{{rows.length}} 项</span><button :disabled="offset+50>=rows.length" @click="offset+=50">下一页</button></div><details v-if="teams.length"><summary>样本队伍 · {{teams.length}} 项</summary><div class="table-scroll"><table><thead><tr><th>角色</th><th>上半/上路数量</th><th>中路数量</th><th>下半/下路数量</th><th>使用率</th></tr></thead><tbody><tr v-for="(t,i) in teams" :key="i"><td>{{t.names.join('、')}}</td><td>{{n(t.up)}}</td><td>{{n(t.middle)}}</td><td>{{n(t.down)}}</td><td>{{n(t.use_rate,'%')}}</td></tr></tbody></table></div></details>
<form v-if="source==='abyss'&&teams.length" class="query-form" @submit.prevent="compare"><label>本人授权角色<select v-model="selection" :disabled="busy"><option value="">选择角色</option><option v-for="r in roles" :key="r.key" :value="r.key">{{r.label}}</option></select></label><button :disabled="busy||!selection">按本人角色匹配深渊配队</button></form><p v-if="error" class="feedback danger" role="alert">{{error}}</p><p v-if="note">{{note}}</p><ol><li v-for="(p,i) in pairs" :key="i"><p>上半：{{p.up.team.names.join('、')}} {{p.up.owned?'':'（缺少角色）'}}</p><p>下半：{{p.down.team.names.join('、')}} {{p.down.owned?'':'（缺少角色）'}}</p><small v-if="p.up.fallback||p.down.fallback">部分武器或天赋字段缺失，使用参考默认值。</small></li></ol></template></section></template>
<style scoped>section{display:grid;gap:16px}label{display:grid;gap:8px;min-width:0}select{min-width:0;width:100%}.table-scroll{overflow-x:auto}table{width:100%;border-collapse:collapse}td,th{text-align:left;padding:10px;border-bottom:1px solid var(--raylea-color-border);white-space:nowrap}li{padding-block:8px}</style>
