<script setup lang="ts">
import { ref, watch } from 'vue'
interface Material { id: string; name: string; family: string; kind: string; rarity: number; city: string; days: number[]; sources: string[]; description: string; related: string[] }
interface Pool { estimated_start?: boolean; version: string; half: string; from: string; to: string; kind: string; characters5: string[]; characters4: string[]; weapons5: string[]; weapons4: string[] }
const props = defineProps<{ game: string; invoke: <T>(action: string, payload?: Record<string, unknown>) => Promise<T> }>()
const query = ref(''), weekday = ref(0), version = ref(''), date = ref(''), materials = ref<Material[]>([]), pools = ref<Pool[]>([]), birthdays = ref<{ name: string; date: string }[]>([]), birthdayDate = ref(''), materialTotal = ref(0), poolTotal = ref(0), sourceVersion = ref(''), busy = ref(false), error = ref('')
const bannerName=ref(''),bannerKind=ref('all'),materialOffset=ref(0),poolOffset=ref(0),materialNext=ref<number|null>(null),poolNext=ref<number|null>(null),appearances=ref<{name:string;kind:string;rarity:number;count:number;last_end:string;days_since_end:number|null}[]>([])
const days = ['','周一','周二','周三','周四','周五','周六','周日']
const kinds: Record<string, string> = { normal: '通用材料', talent: '天赋材料', weapon: '武器材料', weekly: '周本材料', gem: '突破宝石', boss: '首领材料', specialty: '地区特产' }
watch([query, weekday], () => { materials.value = []; materialTotal.value = 0; materialOffset.value=0;materialNext.value=null })
watch([version, date, bannerName, bannerKind], () => { pools.value = []; birthdays.value = []; poolTotal.value = 0;poolOffset.value=0;poolNext.value=null;appearances.value=[] })
async function run(fn: () => Promise<void>) { if (busy.value) return; busy.value = true; error.value = ''; try { await fn() } catch (cause) { error.value = cause instanceof Error ? cause.message : '资料读取失败。' } finally { busy.value = false } }
async function loadMaterials(next=0) { const result = await props.invoke<{ materials: Material[]; total: number; version: string;next_offset?:number|null }>('materials.query', { query: query.value, weekday: Number(weekday.value),offset:next }); materialOffset.value=next;materialNext.value=result.next_offset??null;materials.value = result.materials; materialTotal.value = result.total; sourceVersion.value = result.version }
async function loadPools(next=0) { const result = await props.invoke<{ pools: Pool[]; total: number; version: string; birthdays: { name: string; date: string }[]; birthday_date: string;next_offset?:number|null;appearances:typeof appearances.value }>('banners.query', { version: version.value, date: date.value,query:bannerName.value,kind:bannerKind.value,offset:next }); poolOffset.value=next;poolNext.value=result.next_offset??null;appearances.value=result.appearances??[];pools.value = result.pools; poolTotal.value = result.total; birthdays.value = result.birthdays; birthdayDate.value = result.birthday_date; sourceVersion.value = result.version }
void run(async () => { if(props.game!=='zzz')await loadMaterials(); await loadPools() })
</script>
<template>
  <section class="resource-library">
    <h2>{{game==='zzz'?'卡池历史':'材料与卡池资料'}}</h2><p class="hint">资料来自固定参考快照 {{ sourceVersion }}，可离线查询，无需 CK。卡池和日期未作在线校准，不代表当前官方活动；日期沿用国服 UTC+8。</p>
    <p v-if="error" role="alert" class="feedback danger">{{ error }}</p>
    <section v-if="game!=='zzz'"><h3>材料查询</h3><form @submit.prevent="run(()=>loadMaterials())"><fieldset :disabled="busy"><legend class="sr-only">材料筛选</legend><label>材料名称、系列或地区<input v-model="query" maxlength="128" type="search"></label><label v-if="game === 'genshin'">轮换副本日<select v-model="weekday"><option :value="0">全部材料</option><option v-for="n in 7" :key="n" :value="n">{{ days[n] }}</option></select></label><button type="submit">查询材料</button></fieldset></form>
      <p class="hint">匹配 {{ materialTotal }} 项，当前页 {{ materials.length }} 项；可用关键词缩小范围。</p>
      <ul class="material-list"><li v-for="item in materials" :key="`${item.kind}:${item.id}:${item.name}`"><details><summary>{{ item.name }} · {{ item.rarity }} 星 <span v-if="item.city">· {{ item.city }}</span></summary><p>{{ kinds[item.kind] || '培养材料' }} · {{ item.family }}</p><p v-if="item.days.length">开放：{{ item.days.map(day => days[day]).join(' / ') }}</p><p v-if="item.sources.length">来源：{{ item.sources.join('；') }}</p><p v-if="item.related.length">相关角色/装备：{{ item.related.join('、') }}</p><p v-if="item.description" class="hint">{{ item.description }}</p></details></li></ul><div class="actions"><button :disabled="busy||materialOffset===0" @click="run(()=>loadMaterials(Math.max(0,materialOffset-100)))">上一页材料</button><button :disabled="busy||materialNext===null" @click="run(()=>loadMaterials(materialNext!))">下一页材料</button></div>
    </section>
    <section><h3>{{game==='genshin'?'版本卡池与生日':'版本卡池'}}</h3><form @submit.prevent="run(()=>loadPools())"><fieldset :disabled="busy"><legend class="sr-only">卡池筛选</legend><label>游戏版本<input v-model="version" maxlength="32" placeholder="如 1.0；留空不限"></label><label>角色或装备名称<input v-model="bannerName" maxlength="128" type="search"></label><label>卡池类别<select v-model="bannerKind"><option value="all">全部</option><option value="character">角色</option><option value="weapon">装备</option></select></label><label>卡池日期<input v-model="date" type="date"></label><button type="submit">查询卡池</button></fieldset></form>
      <p v-if="game!=='zzz'" class="hint">{{ birthdayDate }} 的固定生日资料：{{ birthdays.map(item => item.name).join('、') || '未收录' }}。日期留空时卡池不限日期，生日按国服今天查询。</p>
      <p class="hint">匹配 {{ poolTotal }} 期，当前页 {{ pools.length }} 期。</p>
      <details v-if="appearances.length"><summary>出现与复刻记录统计</summary><p class="hint">按收录记录统计次数；距离最近收录结束的天数，不证明此后没有复刻。</p><ul class="material-list"><li v-for="item in appearances" :key="item.kind+item.name"><strong>{{item.name}}</strong> · 收录 {{item.count}} 次 · 最近结束 {{item.last_end}}<span v-if="item.days_since_end!==null"> · 距今 {{item.days_since_end}} 天</span></li></ul></details>
      <ul class="pool-list"><li v-for="(item, index) in pools" :key="`${item.version}:${item.from}:${index}`"><h4>{{ item.version }} · {{ item.half }}{{ item.kind === 'chronicled' ? ' · 集录祈愿' : '' }}</h4><p class="hint">{{ item.from || '未注明开始时间' }} — {{ item.to || '未注明结束时间' }}</p><p v-if="item.estimated_start" class="hint">开始时间按固定参考规则估算。</p><p v-if="item.characters5.length">{{game==='zzz'?'S 级':'五星'}}角色：{{ item.characters5.join('、') }}</p><p v-if="item.characters4.length">{{game==='zzz'?'A 级':'四星'}}角色：{{ item.characters4.join('、') }}</p><p v-if="item.weapons5.length">{{game==='zzz'?'S 级':'五星'}}装备：{{ item.weapons5.join('、') }}</p><p v-if="item.weapons4.length">{{game==='zzz'?'A 级':'四星'}}装备：{{ item.weapons4.join('、') }}</p></li></ul>
      <div class="actions"><button :disabled="busy||poolOffset===0" @click="run(()=>loadPools(Math.max(0,poolOffset-50)))">上一页卡池</button><button :disabled="busy||poolNext===null" @click="run(()=>loadPools(poolNext!))">下一页卡池</button></div>
    </section>
  </section>
</template>
<style scoped>
.resource-library{display:grid;gap:22px}.resource-library>section{display:grid;gap:16px}.resource-library fieldset{display:flex;gap:12px;align-items:end;flex-wrap:wrap;border:0;padding:0;min-width:0}.resource-library label{display:grid;gap:8px;flex:1 1 180px;min-width:0}.material-list,.pool-list{list-style:none;padding:0;display:grid;gap:12px}.material-list li,.pool-list li{padding:14px 0;border-top:1px solid var(--raylea-color-border,#ddd);overflow-wrap:anywhere}.material-list p,.pool-list p{margin-top:8px}.sr-only{position:absolute;width:1px;height:1px;overflow:hidden;clip-path:inset(50%)}
</style>
